### ISSUE TITLE
Classification model for mouse?

### ISSUE THREAD

**Issue by YiweiNiu** [aryarm/varCA#22]
Hi,

Thank you for developing this useful tool. I would like to use `varCA` for mouse samples.

Can I use the current classification model?

If the answer is no, could you give me some advice on training a SNP model for mouse?

Thank you for your effort.

Bests,
Yiwei

**Comment by gmcvicker** [comment]
We think the current classification model should work, but have not tried it on mouse. Please go ahead and try it and let us know if you have any questions or run into any problems.
