### ISSUE TITLE
VarDict-java produces malformed VCF

### ISSUE THREAD

**Issue by aryarm** [aryarm/varCA#42]
I'm creating this issue to record a problem encountered by a user through personal correspondence. They received the following error message:

> htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 165135: unparsable vcf record with allele CCCCCTCCCCACTGTTCCAGTAGTCACTCCCTGGCTCCTCCCCAGGCCTCT\<dup-8\>AGGCCTCTGCTGCTCCTCCCCACTGTGTTCCAGTAGTCACTCCCTGGCTG

Based on the error message, it sounds like the VarDict-java tool is creating a malformed VCF allele:
> CCCCCTCCCCACTGTTCCAGTAGTCACTCCCTGGCTCCTCCCCAGGCCTCT\<dup-8\>AGGCCTCTGCTGCTCCTCCCCACTGTGTTCCAGTAGTCACTCCCTGGCTG

The `<dup-8>` part of that allele is not valid in the VCF format, so GATK flags it and raises an exception.

It appears that someone else has already reported the issue in [the VarDict repo](https://github.com/AstraZeneca-NGS/VarDictJava/issues/342). In the meantime, if anyone else encounters this while we wait for the issue to be resolved, I would recommend just discarding those alleles manually using `awk` just like we did in #25 . For example, you could edit [line 17 of the `callers/vardict` file](https://github.com/aryarm/varCA/blob/fcf59091a2032fa0126b446991d68de6683f73e3/callers/vardict#L17) from this
```
teststrandbias.R | var2vcf_valid.pl | bgzip > "$output_dir/vardict.vcf.gz" && \
```
to this
```
teststrandbias.R | var2vcf_valid.pl | \
awk -F $"\t" -v 'OFS=\t' '/^#/ || $5 !~ /<dup/' | \
bgzip > "$output_dir/vardict.vcf.gz" && \
```
This will simply remove any lines in the VCF where the fifth column (for the ALT alleles) contains `<dup`. Ideally, we would keep those lines in the file and fix those alleles so that they are valid, since they potentially represent real structural variants that should be reported in VarCA's output. But without further information, I can't know what the correct allele should be, so I don't know how to properly change it using `awk`.

**Comment by aryarm** [comment]
ooops, I meant to delete the `varscan.vcf` portion on the second line of that code snippet! Here's the corrected version
```
teststrandbias.R | var2vcf_valid.pl | \
awk -F $"\t" -v 'OFS=\t' '/^#/ || $5 !~ /<dup/' | \
bgzip > "$output_dir/vardict.vcf.gz" && \
```
Sorry about that!

**Comment by elahoehne** [comment]
Thank you very much!
Now it run successfully! There is only a warning occurring:

`scripts/2vcf.py:267: UserWarning: Ignored 32116410 classification sites that didn't have a variant.
#  "Ignored {:n} classification sites that didn't have a variant.".format(skipped)
`

But I guess that makes sense!? 
I am now running it with the merged fastq files.

**Comment by aryarm** [comment]
Yes, that is a standard warning message that will happen regardless of the Vardict issue. When generating a VCF, VarCA will keep track of every position in the genome, regardless of whether there's a variant there. The 2vcf.py script will then discard these sites when it converts the final output to VCF.

**Comment by elahoehne** [comment]
Now it worked for all replicates as well as for the merged fastq files! 
Thank you very much for your help!
